{% set version = "1.15.2" %}

package:
  name: firecrown
  version: {{ version }}

source:
  url: https://github.com/LSSTDESC/firecrown/releases/download/v{{ version }}/firecrown-{{ version }}.tar.gz
  sha256: e43c03927da36610e57f97a256244df3d18aeff021682c1b162b5d24eab6f1aa

build:
  skip: true  # [win or py<311]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools
    - setuptools-scm
  run:
    - charset-normalizer
    - clmm
    - cosmosis >=3.0.0
    - cosmosis-build-standard-library
    - cython
    - dill
    - fitsio
    - fuzzywuzzy
    - getdist
    - idna
    - matplotlib-base
    - more-itertools
    - numcosmo >=0.21.1
    - numpy >=2.0
    - portalocker
    - pybobyqa
    - pyccl >=2.8.0
    - pydantic
    - python
    - pyyaml
    - requests
    - rich
    - sacc >=2.1
    - scipy >=1.12
    - tabulate
    - typer
    - types-pyyaml
    - urllib3

test:
  imports:
    - firecrown
  commands:
    - python -c "import firecrown, importlib.metadata as md; assert firecrown.__version__ == '{{ version }}'; assert md.version('firecrown') == '{{ version }}'"

about:
  home: https://github.com/LSSTDESC/firecrown
  license: BSD-3-Clause
  license_file: LICENSE
  summary: DESC Cosmology Likelihood Framework

extra:
  recipe-maintainers:
    - marcpaterno
    - vitenti
    - beckermr
